# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-01 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('numero', 'tipo'),
            },
        ),
    ]
