# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-03 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartao_membro', models.IntegerField()),
                ('tipo', models.CharField(choices=[('dirigente', 'Dirigente'), ('vice-dirigente', 'Vice-dirigente'), ('secretario', 'Secretario'), ('vice-secretario', 'Vice-secretário'), ('tesoureiro', 'Tesoureiro'), ('vice-tesoureiro', 'Vice-tesoureiro'), ('vice-coordenadora', 'Vice-coordenadora'), ('professor', 'Professor'), ('adjunto', 'Adjunto'), ('secretario-local', 'Secretario Local'), ('aluno', 'Aluno'), ('coordenadora', 'Coordenadora')], default='aluno', max_length=50, verbose_name='Type')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=15)),
                ('nascimento', models.DateField()),
                ('logradouro', models.CharField(max_length=100)),
                ('numero_end', models.IntegerField()),
                ('complemento_end', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(max_length=50)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.Classe')),
            ],
        ),
    ]
