# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-03 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_auto_20171102_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ('numero', 'departamento')},
        ),
        migrations.AlterModelOptions(
            name='componente',
            options={'ordering': ('nome',)},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ('nome',)},
        ),
        migrations.RemoveField(
            model_name='classe',
            name='tipo',
        ),
        migrations.AddField(
            model_name='classe',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.Departamento'),
        ),
        migrations.AddField(
            model_name='classe',
            name='faixa',
            field=models.CharField(choices=[('adulto', 'Adulto'), ('jovens', 'Jovens'), ('adolescentes', '13 e 14 anos'), ('juvenis', '15 a 17 anos'), ('juniores', '9 e 10 anos'), ('maternal', '3 e 4 anos')], default='adulto', max_length=50),
        ),
    ]
