# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-03 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_auto_20171103_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.Departamento'),
        ),
    ]
