# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0006_auto_20171103_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data_evento', models.DateField()),
            ],
            options={
                'ordering': ('titulo', 'data_evento'),
            },
        ),
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ('numero', 'departamento', 'faixa')},
        ),
        migrations.AlterField(
            model_name='componente',
            name='complemento_end',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='numero_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='tipo',
            field=models.CharField(choices=[('dirigente', 'Dirigente'), ('vice-dirigente', 'Vice-dirigente'), ('secretario', 'Secretario'), ('vice-secretario', 'Vice-secretário'), ('tesoureiro', 'Tesoureiro'), ('vice-tesoureiro', 'Vice-tesoureiro'), ('vice-coordenadora', 'Vice-coordenadora'), ('professor', 'Professor'), ('adjunto', 'Adjunto'), ('secretario-local', 'Secretario Local'), ('aluno', 'Aluno'), ('coordenadora', 'Coordenadora')], default='aluno', max_length=50, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='uf',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UF'),
        ),
    ]
