# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 04:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0007_auto_20171115_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caderneta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime(2017, 11, 16, 1, 24, 27, 30728))),
                ('presentes', models.IntegerField(blank=True, null=True)),
                ('visitantes', models.IntegerField(blank=True, null=True)),
                ('matriculados', models.IntegerField(blank=True, null=True)),
                ('biblias', models.IntegerField(blank=True, null=True)),
                ('professor', models.IntegerField(blank=True, null=True)),
                ('adjuntos', models.IntegerField(blank=True, null=True)),
                ('atendimento', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('data',),
            },
        ),
    ]
