# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 04:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0008_caderneta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caderneta',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 11, 16, 4, 28, 2, 922496, tzinfo=utc)),
        ),
    ]
