# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 04:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0009_auto_20171116_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caderneta',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
