# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0010_auto_20171116_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='caderneta',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Normal'), ('manha-missionaria', 'Manhã Missionária'), ('classe-unica', 'Classe única'), ('escola-animada', 'Escola Animada')], default='normal', max_length=50, verbose_name='Tipo'),
        ),
    ]
