# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 03:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0012_auto_20171118_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadernetaGeral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('manha-missionaria', 'Manhã Missionária'), ('classe-unica', 'Classe única'), ('escola-animada', 'Escola Animada')], default='normal', max_length=50, verbose_name='Tipo')),
                ('data', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AlterModelOptions(
            name='caderneta',
            options={'ordering': ('classe',)},
        ),
        migrations.RemoveField(
            model_name='caderneta',
            name='data',
        ),
        migrations.RemoveField(
            model_name='caderneta',
            name='tipo',
        ),
        migrations.AddField(
            model_name='caderneta',
            name='caderneta_geral',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='caderneta_geral', to='escola.CadernetaGeral'),
            preserve_default=False,
        ),
    ]
