# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0013_auto_20171203_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caderneta',
            old_name='caderneta_geral',
            new_name='domingo',
        ),
    ]
